---
title: Daryl Shaw
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  blog_tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
  notes:
    title: Notes
    output: true
  photos:
    title: Photos
    output: true
defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
    permalink: "/blog/:title/"
    post_type: "Article"
-
  scope:
    path: ""
    type: "blog_tags"
  values:
    layout: "tag"
-
  scope:
    path: ""
    type: "notes"
  values:
    layout: "note"
    title: ""
    permalink: "/:collection/:title/"
    post_type: "Note"
-
  scope:
    path: ""
    type: "photos"
  values:
    layout: "photo"
    title: ""
    permalink: "/:collection/:title/"
    post_type: "Photo"
url: https://darylshaw.co.uk
permalink: pretty
fathom_analytics: JNJBHQAI
name: Daryl Shaw
email: daryl@darylshaw.co.uk
twitter:
  username: daryl_shaw
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-paginate-v2
- jekyll-mentions
repository: darylshaw/darylshaw.co.uk
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 5
  permalink: 'page/:num/'
  limit: 1
feed_items: 10
jekyll-mentions:
  base_url: https://twitter.com
exclude: [README.md, Gruntfile.js, package.json, package-lock.json, netlify.toml]
redirect_from:
  json: false
